version: "3.9"
services:
  # jenkins:
  #   container_name: JENKINS
  #   image: jenkins/jenkins:jdk17
  #   ports:
  #     - "${JENKINS_EXPORT_PORT_HTTP}:8080"
  #     - "${JENKINS_EXPORT_PORT_WEBSOCKET}:50000"

  app:
    container_name: APP
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - APP_USER=${APP_USER}
        - APP_PASSWORD=${APP_PASSWORD}
        - API_EXPOSE_PORT=${API_EXPOSE_PORT}
    ports:
      - "${API_EXPOSE_PORT}:${API_EXPOSE_PORT}"
      - "${SSH_EXPOSE_PORT}:22"
    stdin_open: true
    tty: true
    restart: always
    environment:
      - APP_USER
      - APP_PASSWORD
      - API_EXPOSE_PORT
      - SSH_EXPOSE_PORT
      # - JENKINS_EXPORT_PORT_HTTP
      # - JENKINS_EXPORT_PORT_WEBSOCKET

#docker-compose up --build -d
