version: "3.9"
services:
  jenkins:
    container_name: JENKINS
    image: jenkins/jenkins:jdk17
    ports:
      - "8080:8080"
      - "50000:50000"

  app:
    container_name: APP
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8083:8083"
    stdin_open: true
    tty: true