name: CI/CD Maven

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Récupération des sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build package
      run: mvn -B -DskipTests package --file pom.xml
    - name: Renommage fichier jar
      run: mv target/*.jar target/api-rest.jar
    - name: Copy build jar to production folder
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/api-rest.jar"
        target: "/home/expernet/app"
    
  launch:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - name: Launch api rest service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sh /home/expernet/app/restart.sh
